### ISSUE TITLE
It seems generate wrong alignment/CIGAR in bedpe results.

### ISSUE THREAD

**Issue by yuanhao0626** [0xTCG/biser#15]
Hi developers, 

Many thanks for develop such useful tool.

I found something wrong in my results of my custom genome, which is it seems that alignments and CIGARs are not fit.

One of the example in bedpe is that:
> Chr01	4418024	4427454	Chr01	180596427	180603749	Fasta:Fasta	1.3	+	+	5411	5413	9M1341S53M3D277M14D666M2I4389M	X=1;ID=0.4

Li Heng wrote that "Sum of lengths of the M/I/S/=/X operations shall equal the length of SEQ." in SAMtools manual, but it seems that the sum of my CIGAR is not equal to neither of the 2 lengths of the alignment.

While minimap2 seems gave the better CIGAR in maf:
> Chr01:4418024-4427454	9431	1350	8483	+	Chr01:180596427-180603749	7323	9	7323	7049	7317	6NM:i:268	ms:i:6640	AS:i:6439	nn:i:0	tp:A:P	cm:i:1016	s1:i:6385	s2:i:452	de:f:0.0123	rl:i:0	cg:Z:54M3D277M14D666M2I4431M150D1149M1I63M3D277M14D213M

fastas of the 2 loci are attached here:
[t.fa.txt](https://github.com/0xTCG/biser/files/9564644/t.fa.txt)
[q.fa.txt](https://github.com/0xTCG/biser/files/9564646/q.fa.txt)

please help about it, thanks very much.

**Comment by inumanag** [comment]
Fixed in 1.3--- thank you for the report!

**Comment by zpliu1126** [comment]
I got 24 millions SD items in the bedpe results. Do I need to filter this results. Because I found that [Evan E. Eichler et al](https://www.science.org/doi/10.1126/science.abj6965) identified SDs using SEDEF and filtered using the following criteria.

+ at least 90% gap-compressed identity
+ at most 50% gapped sequence in the alignment
+ at least 1 kbp of aligned sequence
+ at most 70% satellite sequence as determined by RepeatMasker

Can I filter the bedpe results with the same criteria? Such as:
+ X≤ 10
+ ID ≤50 
+  columns 12 in the bedpe  file ≥1000 bp
+ the ratio of masked based that located in the SD region ≤ 70%

**Comment by inumanag** [comment]
No idea—you will gave to ask the authors of that paper how did they do their analysis. I don't think it's that simple, unfortunately.

**Comment by zpliu1126** [comment]
Do the results in the bedpe file need to be filtered, and can they be directly used for downstream analysis？

**Comment by inumanag** [comment]
We use them directly. However, it really depends on your study/application: for us, 75% similarity is what we wanted.

**Comment by SLin191** [comment]
> We use them directly. However, it really depends on your study/application: for us, 75% similarity is what we wanted.

Is "75% similarity" the score value of column 8 in the result file?

If score value is 25, this mean 75% similarity. Is it?

**Comment by inumanag** [comment]
Correct. Note that BISER sometimes can output values slightly higher than 25%.
